[package]
name = "boxkv-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util"] }
async-trait = "0.1"

[dev-dependencies]
tempfile = { workspace = true }