// This file is @generated by prost-build.
/// / Wasm 插件执行计划
/// / 用于指定在各个 Hook 点执行哪些插件（通过 UUID）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmPlan {
    /// PreWrite Hook 插件列表
    #[prost(string, repeated, tag = "1")]
    pub pre_write: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// PostWrite Hook 插件列表
    #[prost(string, repeated, tag = "2")]
    pub post_write: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// OnRead Hook 插件列表
    #[prost(string, repeated, tag = "3")]
    pub on_read: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// ScanFilter Hook 插件列表（预留）
    #[prost(string, repeated, tag = "4")]
    pub scan_filter: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Put 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutRequest {
    /// 键（原始字节）
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// 值（原始字节）
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// Wasm 执行计划（可选）
    #[prost(message, optional, tag = "5")]
    pub plan: ::core::option::Option<WasmPlan>,
    /// 过期时间（二选一）
    #[prost(oneof = "put_request::Expiry", tags = "3, 4")]
    pub expiry: ::core::option::Option<put_request::Expiry>,
}
/// Nested message and enum types in `PutRequest`.
pub mod put_request {
    /// 过期时间（二选一）
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Expiry {
        /// 相对 TTL（秒）
        #[prost(uint64, tag = "3")]
        TtlSecs(u64),
        /// 绝对过期时间戳（秒）
        #[prost(uint64, tag = "4")]
        ExpiresAt(u64),
    }
}
/// / Put 响应
///
/// 成功则为空，失败通过 gRPC Status 返回
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PutResponse {}
/// / Get 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRequest {
    /// 键（原始字节）
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// Wasm 执行计划（可选）
    #[prost(message, optional, tag = "2")]
    pub plan: ::core::option::Option<WasmPlan>,
}
/// / Get 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetResponse {
    /// 是否找到
    #[prost(bool, tag = "1")]
    pub found: bool,
    /// 值（仅 found=true 时有效）
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// / Delete 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRequest {
    /// 键（原始字节）
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// Wasm 执行计划（可选）
    #[prost(message, optional, tag = "2")]
    pub plan: ::core::option::Option<WasmPlan>,
}
/// / Delete 响应
///
/// 成功则为空，失败通过 gRPC Status 返回
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteResponse {}
/// / WriteBatch 单条操作
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteBatchOp {
    /// 操作类型
    #[prost(enumeration = "OpType", tag = "1")]
    pub op: i32,
    /// 键（原始字节）
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// 值（仅 PUT 时有效）
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// 过期时间（二选一，仅 PUT 时有效）
    #[prost(oneof = "write_batch_op::Expiry", tags = "4, 5")]
    pub expiry: ::core::option::Option<write_batch_op::Expiry>,
}
/// Nested message and enum types in `WriteBatchOp`.
pub mod write_batch_op {
    /// 过期时间（二选一，仅 PUT 时有效）
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Expiry {
        /// 相对 TTL（秒）
        #[prost(uint64, tag = "4")]
        TtlSecs(u64),
        /// 绝对过期时间戳（秒）
        #[prost(uint64, tag = "5")]
        ExpiresAt(u64),
    }
}
/// / WriteBatch 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteBatchRequest {
    /// 操作列表（保序执行）
    #[prost(message, repeated, tag = "1")]
    pub ops: ::prost::alloc::vec::Vec<WriteBatchOp>,
    /// Wasm 执行计划（批内共享）
    #[prost(message, optional, tag = "2")]
    pub plan: ::core::option::Option<WasmPlan>,
}
/// / WriteBatch 响应
///
/// 成功则为空，失败通过 gRPC Status 返回
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WriteBatchResponse {}
/// / 插件上传请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadRequest {
    /// 插件名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 插件版本（语义化版本）
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Hook 类型（PreWrite/PostWrite/OnRead/ScanFilter）
    #[prost(string, tag = "3")]
    pub hook: ::prost::alloc::string::String,
    /// Wasm 二进制（完整模块）
    #[prost(bytes = "vec", tag = "4")]
    pub wasm: ::prost::alloc::vec::Vec<u8>,
}
/// / 插件上传响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadResponse {
    /// 生成的插件 ID（UUIDv5）
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    /// Wasm 二进制指纹（SHA256）
    #[prost(string, tag = "2")]
    pub fingerprint: ::prost::alloc::string::String,
}
/// / 插件确认请求（重启后校验）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnsureRequest {
    /// 插件名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 插件版本
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Hook 类型
    #[prost(string, tag = "3")]
    pub hook: ::prost::alloc::string::String,
    /// 期望的指纹（用于校验）
    #[prost(string, tag = "4")]
    pub fingerprint: ::prost::alloc::string::String,
}
/// / 插件确认响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnsureResponse {
    /// 插件是否存在
    #[prost(bool, tag = "1")]
    pub exists: bool,
    /// 插件 ID（exists=true 时有效）
    #[prost(string, tag = "2")]
    pub plugin_id: ::prost::alloc::string::String,
    /// 指纹是否匹配（exists=true 时有效）
    #[prost(bool, tag = "3")]
    pub fingerprint_match: bool,
}
/// / 获取最新插件请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestRequest {
    /// 插件名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Hook 类型
    #[prost(string, tag = "2")]
    pub hook: ::prost::alloc::string::String,
}
/// / 获取最新插件响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestResponse {
    /// 是否找到
    #[prost(bool, tag = "1")]
    pub found: bool,
    /// 最新插件 ID（found=true 时有效）
    #[prost(string, tag = "2")]
    pub plugin_id: ::prost::alloc::string::String,
    /// 最新版本号（found=true 时有效）
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// 最新指纹（found=true 时有效）
    #[prost(string, tag = "4")]
    pub fingerprint: ::prost::alloc::string::String,
}
/// / 清除插件请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurgeRequest {
    /// 插件名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 要清除的大版本号（0 表示全部）
    #[prost(uint32, tag = "2")]
    pub major_version: u32,
}
/// / 清除插件响应
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PurgeResponse {
    /// 清除的插件数量
    #[prost(uint32, tag = "1")]
    pub purged_count: u32,
}
/// / WriteBatch 操作类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpType {
    /// Put 操作
    OpPut = 0,
    /// Delete 操作
    OpDelete = 1,
}
impl OpType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OpPut => "OP_PUT",
            Self::OpDelete => "OP_DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OP_PUT" => Some(Self::OpPut),
            "OP_DELETE" => Some(Self::OpDelete),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod box_kv_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BoxKvServer.
    #[async_trait]
    pub trait BoxKv: std::marker::Send + std::marker::Sync + 'static {
        /// / 写入单条记录
        async fn put(
            &self,
            request: tonic::Request<super::PutRequest>,
        ) -> std::result::Result<tonic::Response<super::PutResponse>, tonic::Status>;
        /// / 读取单条记录
        async fn get(
            &self,
            request: tonic::Request<super::GetRequest>,
        ) -> std::result::Result<tonic::Response<super::GetResponse>, tonic::Status>;
        /// / 删除单条记录
        async fn delete(
            &self,
            request: tonic::Request<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status>;
        /// / 批量写入
        async fn write_batch(
            &self,
            request: tonic::Request<super::WriteBatchRequest>,
        ) -> std::result::Result<tonic::Response<super::WriteBatchResponse>, tonic::Status>;
    }
    /// / BoxKV 核心服务
    #[derive(Debug)]
    pub struct BoxKvServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BoxKvServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BoxKvServer<T>
    where
        T: BoxKv,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/boxkv.v1.BoxKV/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: BoxKv>(pub Arc<T>);
                    impl<T: BoxKv> tonic::server::UnaryService<super::PutRequest> for PutSvc<T> {
                        type Response = super::PutResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as BoxKv>::put(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.BoxKV/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: BoxKv>(pub Arc<T>);
                    impl<T: BoxKv> tonic::server::UnaryService<super::GetRequest> for GetSvc<T> {
                        type Response = super::GetResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as BoxKv>::get(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.BoxKV/Delete" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSvc<T: BoxKv>(pub Arc<T>);
                    impl<T: BoxKv> tonic::server::UnaryService<super::DeleteRequest> for DeleteSvc<T> {
                        type Response = super::DeleteResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as BoxKv>::delete(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.BoxKV/WriteBatch" => {
                    #[allow(non_camel_case_types)]
                    struct WriteBatchSvc<T: BoxKv>(pub Arc<T>);
                    impl<T: BoxKv> tonic::server::UnaryService<super::WriteBatchRequest> for WriteBatchSvc<T> {
                        type Response = super::WriteBatchResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WriteBatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as BoxKv>::write_batch(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WriteBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(empty_body());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for BoxKvServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "boxkv.v1.BoxKV";
    impl<T> tonic::server::NamedService for BoxKvServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated server implementations.
pub mod plugin_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PluginServer.
    #[async_trait]
    pub trait Plugin: std::marker::Send + std::marker::Sync + 'static {
        /// / 上传插件
        async fn upload(
            &self,
            request: tonic::Request<super::UploadRequest>,
        ) -> std::result::Result<tonic::Response<super::UploadResponse>, tonic::Status>;
        /// / 确认插件存在（重启后校验）
        async fn ensure(
            &self,
            request: tonic::Request<super::EnsureRequest>,
        ) -> std::result::Result<tonic::Response<super::EnsureResponse>, tonic::Status>;
        /// / 获取最新插件
        async fn get_latest(
            &self,
            request: tonic::Request<super::GetLatestRequest>,
        ) -> std::result::Result<tonic::Response<super::GetLatestResponse>, tonic::Status>;
        /// / 清除插件
        async fn purge(
            &self,
            request: tonic::Request<super::PurgeRequest>,
        ) -> std::result::Result<tonic::Response<super::PurgeResponse>, tonic::Status>;
    }
    /// / 插件管理服务
    #[derive(Debug)]
    pub struct PluginServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PluginServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PluginServer<T>
    where
        T: Plugin,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/boxkv.v1.Plugin/Upload" => {
                    #[allow(non_camel_case_types)]
                    struct UploadSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::UploadRequest> for UploadSvc<T> {
                        type Response = super::UploadResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UploadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as Plugin>::upload(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UploadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.Plugin/Ensure" => {
                    #[allow(non_camel_case_types)]
                    struct EnsureSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::EnsureRequest> for EnsureSvc<T> {
                        type Response = super::EnsureResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnsureRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as Plugin>::ensure(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EnsureSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.Plugin/GetLatest" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::GetLatestRequest> for GetLatestSvc<T> {
                        type Response = super::GetLatestResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLatestRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Plugin>::get_latest(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLatestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/boxkv.v1.Plugin/Purge" => {
                    #[allow(non_camel_case_types)]
                    struct PurgeSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::PurgeRequest> for PurgeSvc<T> {
                        type Response = super::PurgeResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PurgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as Plugin>::purge(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PurgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(empty_body());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for PluginServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "boxkv.v1.Plugin";
    impl<T> tonic::server::NamedService for PluginServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
